### ISSUE TITLE
XLX Support Vanished

### ISSUE THREAD

**Issue by K2IE** [HBLink-org/hblink3#1]
Sometme after commit 08f6669bd315f8abb9bd80b5faad4cd43439c2f4, XLX support has vanished.  Confirmed locally by a hard reset and XLX support is there.

**Comment by randybuildsthings** [comment]
Is it possible for you to look through the commit history and locate what changed? I'm curious what exactly is meant by "XLX Support" here.

Next step would be to create a pull request to get it applied to the code base, assuming it makes sense to do so.

**Comment by randybuildsthings** [comment]
Okay, found it.

Apparently, Cort decided back in commit 89040e7c14d3d2b356cb2bcccce4650ef4571807 that the XLX code was "cruft". We can bring it back without issue, I think. If you can create a pull request to review that, I'd be okay to look it over and merge it.

**Comment by randybuildsthings** [comment]
Looks like XLX code is back. No harm, no foul.
