### ISSUE TITLE
Problem connectig to hblink

### ISSUE THREAD

**Issue by bouab002** [HBLink-org/hblink3#3]
Hello;I have problems connecting to another Hblink server, the server restarts the authentication very 1S connection is working and I get the QSO.

http://137.74.195.150:8080

COFIG:

[DMR-FRANCOPHONE]
MODE: PEER
ENABLED: True
LOOSE: False
EXPORT_AMBE: False
IP:
PORT: 54004
MASTER_IP: 137.74.195.150
MASTER_PORT: 62030
PASSPHRASE: passw0rd
CALLSIGN: FXXXX
RADIO_ID: 2080XXX99
RX_FREQ: 443900000
TX_FREQ: 443900000
TX_POWER: 25
COLORCODE: 1
SLOTS: 1
LATITUDE: XX.XXXX
LONGITUDE: X.XXXX
HEIGHT: 75
LOCATION: XXXXXX,XXXXx
DESCRIPTION: HBlink 
URL: XXXXXXXXXXXXXXX
SOFTWARE_ID: 20170620
PACKAGE_ID: MMDVM_HBlink
GROUP_HANGTIME: 5
OPTIONS:
USE_ACL: True
SUB_ACL: DENY:1
TGID_TS1_ACL: PERMIT:ALL
TGID_TS2_ACL: PERMIT:ALL

LOGS:

INFO 2020-10-31 11:35:32,445 (DMR-FRANCOPHONE) Repeater Authentication Accepted
INFO 2020-10-31 11:35:32,446 (DMR-FRANCOPHONE) Repeater Configuration Sent
INFO 2020-10-31 11:35:32,459 (DMR-FRANCOPHONE) Repeater Configuration Accepted
INFO 2020-10-31 11:35:32,460 (DMR-FRANCOPHONE) Sent options: (b'Type=HBlink;')
INFO 2020-10-31 11:35:37,414 (DMR-FRANCOPHONE) Sending login request to master 137.74.195.150:62030
INFO 2020-10-31 11:35:37,429 (DMR-FRANCOPHONE) Repeater Login ACK Received with 32bit ID: 4084617675
INFO 2020-10-31 11:35:37,443 (DMR-FRANCOPHONE) Repeater Authentication Accepted
INFO 2020-10-31 11:35:37,443 (DMR-FRANCOPHONE) Repeater Configuration Sent
INFO 2020-10-31 11:35:37,457 (DMR-FRANCOPHONE) Repeater Configuration Accepted
INFO 2020-10-31 11:35:37,458 (DMR-FRANCOPHONE) Sent options: (b'Type=HBlink;')
INFO 2020-10-31 11:35:42,416 (DMR-FRANCOPHONE) Sending login request to master 137.74.195.150:62030
INFO 2020-10-31 11:35:42,431 (DMR-FRANCOPHONE) Repeater Login ACK Received with 32bit ID: 2731809743
INFO 2020-10-31 11:35:42,445 (DMR-FRANCOPHONE) Repeater Authentication Accepted
INFO 2020-10-31 11:35:42,446 (DMR-FRANCOPHONE) Repeater Configuration Sent
INFO 2020-10-31 11:35:42,460 (DMR-FRANCOPHONE) Repeater Configuration Accepted
INFO 2020-10-31 11:35:42,462 (DMR-FRANCOPHONE) Sent options: (b'Type=HBlink;')
INFO 2020-10-31 11:35:47,415 (DMR-FRANCOPHONE) Sending login request to master 137.74.195.150:62030
INFO 2020-10-31 11:35:47,430 (DMR-FRANCOPHONE) Repeater Login ACK Received with 32bit ID: 859213554
INFO 2020-10-31 11:35:47,444 (DMR-FRANCOPHONE) Repeater Authentication Accepted
INFO 2020-10-31 11:35:47,445 (DMR-FRANCOPHONE) Repeater Configuration Sent
INFO 2020-10-31 11:35:47,459 (DMR-FRANCOPHONE) Repeater Configuration Accepted
INFO 2020-10-31 11:35:47,461 (DMR-FRANCOPHONE) Sent options: (b'Type=HBlink;')

Regards,
F4IRF

**Comment by bouab002** [comment]
commit to git checkout  d68241918b95944544d2ef9e661a615d98b5c92a  solved my problem

**Comment by randybuildsthings** [comment]
Just going to state that if you're connecting to another HBLink instance, you really should look at using OpenBridge and setting it up the connection that way (much like you would with any of the DVSwitch services), rather than having HBLink masquerade as a peer/repeater on a master server. There is the option in OpenBridge of passing traffic on both slots 1 & 2, rather than just slot 1 (which is how BrandMeister wants to use OpenBridge connections).
