### ISSUE TITLE
HBlink incorrecly sees data as new group call from XLX when none sent

### ISSUE THREAD

**Issue by K2IE** [HBLink-org/hblink3#4]
As discussed on the groups.io mailing list and submitted with some additional data.

At the end of any transmission to a bridge group in which an XLXPEER participates, HBlink thinks the XLX is sending a brief new group call in response to the end of the original stream.  I am fairly certain (through packet capture) that there are no out of sequence packets being sent back from the XLX.

HBlink is somehow confused by what it thinks it sees.  This results in artifacts of a new transmission in the log when none was went.  It gets in the way of private calls working properly, as calls get forwarded to the XLX (where the desired recpient is not).

Configs and other data follow:

Log evidence:

INFO 2020-10-27 09:40:24,091 (HOTSPOTS) *GROUP CALL START* STREAM ID: 3158937644 SUB: K2IE (3134090) PEER: 313409002 (313409002) TGID 2 (2), TS 2
INFO 2020-10-27 09:40:24,095 (HOTSPOTS) Conference Bridge: TEST BRIDGE, Call Bridged to HBP System: XLX020E TS: 2, TGID: 2
INFO 2020-10-27 09:40:29,990 (HOTSPOTS) *GROUP CALL END*   STREAM ID: 3158937644 SUB: K2IE (3134090) PEER: 313409002 (313409002) TGID 2 (2), TS 2, Duration: 5.90
INFO 2020-10-27 09:40:30,021 (XLX020E) *GROUP CALL START* STREAM ID: 3158900736 SUB: K2IE (3134090) PEER: 3163081 (3163081) TGID 9 (9), TS 2

Config:

[HOTSPOTS]
MODE: MASTER
ENABLED: True
REPEAT: True
MAX_PEERS: 10
EXPORT_AMBE: False
IP:
PORT: 54100
PASSPHRASE: passw0rd
GROUP_HANGTIME: 5
USE_ACL: True
REG_ACL: DENY:1
SUB_ACL: DENY:1
TGID_TS1_ACL: PERMIT:ALL
TGID_TS2_ACL: PERMIT:ALL

Ok to test against XLX020E for this issue

[XLX020E]
MODE: XLXPEER
ENABLED: True
LOOSE: True
EXPORT_AMBE: False
IP:
PORT: 54002
MASTER_IP: 66.175.215.217
MASTER_PORT: 62030
PASSPHRASE: passw0rd
CALLSIGN: YOUR_VALID_CALL
RADIO_ID: YOUR_VALID_RID
RX_FREQ: 449000000
TX_FREQ: 444000000
TX_POWER: 25
COLORCODE: 1
SLOTS: 1
LATITUDE: 38.0000
LONGITUDE: -095.0000
HEIGHT: 75
LOCATION: Anywhere, USA
DESCRIPTION: Test config
URL: www.w1abc.org
SOFTWARE_ID: 20170620
PACKAGE_ID: MMDVM_HBlink
GROUP_HANGTIME: 5
XLXMODULE: 4005
USE_ACL: True
SUB_ACL: DENY:1
TGID_TS1_ACL: PERMIT:ALL
TGID_TS2_ACL: PERMIT:ALL

Rules:

BRIDGES = {
    'TEST BRIDGE': [
            {'SYSTEM': 'HOTSPOTS',    'TS': 2, 'TGID': 2,    'ACTIVE': True, 'TIMEOUT': 2, 'TO_TYPE': 'NONE',  'ON': [], 'OFF': [], 'RESET': []},

[xlxd.zip](https://github.com/HBLink-org/hblink3/files/5469675/xlxd.zip)
            {'SYSTEM': 'XLX020E',    'TS': 2, 'TGID': 2,    'ACTIVE': True, 'TIMEOUT': 2, 'TO_TYPE': 'NONE',  'ON': [], 'OFF': [], 'RESET': []},
        ]
}

UNIT = ['HOTSPOTS', 'XLX020E']

Wireshark capture done on the XLX attached so show how the sequence numbers are being properly incremented from the XLX end.  See xlxd.zip.

**Comment by sp2ong** [comment]
It looks like it is problem XLXD

https://github.com/LX3JL/xlxd/issues/123

https://dvswitch.groups.io/g/HBlink/topic/32158218#455

**Comment by K2IE** [comment]
Luc (LX1IQ) states that he will be addressing this issue in the near future.  As the fix pertains to xlxd rather than HBlink, I will close this issue.
